variables:
    IMAGE_NAME: registry.gitlab.com/twn-devsecops-bootcamp/latest/juice-shop
    IMAGE_TAG: juice-shop-1.1
stages:
    - test
    - build

yarn_test:
    image: node:18-bullseye
    stage: test
    script:
        - yarn install
        - yarn test

build_image:
    stage: build
    image: docker:24
    services:
       - docker:24-dind
    variables:
        DOCKER_PASS: Rostelekom1q2w3e
        DOCKER_USER: abobus1337
    before_script:
        - echp "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
