variables:
    IMAGE_NAME: torsami77/juice_shop
    IMAGE_TAG: version.0.1
stages:
    - cache
    - test
    - build

create-cache:
    stage: cache
    image: node:18-bullseye
    script:
        - yarn install
    cache:
        key: # changes that toggles the cache recreation
            files:
                - yarn-lock
        paths: # files to cache when changes occur
            - node_modules/
            - yarn-lock
            - .yarn
        policy: pull-push  # this policy describes that the create-cache pulls and push cache update

yarn-test:
    stage: test
    image: node:18-bullseye
    script:
        - yarn install
        - yarn test
    ##### reusing the cache config to leverage cache
    cache:
        key: # changes that toggles the cache recreation
            files:
                - yarn-lock
        paths: # files to cache when changes occur
            - node_modules/
            - yarn-lock
            - .yarn
        policy: pull  # change policy to pull only to implement cache

git_leaks:
    stage: test
    image:
        name: zricethezav/gitleaks
        entrypoint: [""]
    script:
        - gitleaks detect --verbose --source .
    allow_failure: true


build_image:
    stage: build
    image: docker:24
    services: 
        - docker:24-dind
    before_script:
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin # variables are gotten from jenkins variable settings
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
