variable:
    IMAGE_NAME: devsecjs/devescops
    IMAGE_TAG: juice-shop-1.1
stages:
  - test
  - build

yarn_test:
  image:  node:18-bullseye
  stage: test
  script:
    - yarn install
    - yarn test

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variable:
    DOCKER_PASS: 1qaz2wsx!QAZ@WSX
    DOCKER_USER: devsecjs
  before_script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

  script:
    - docker build -t devsecjs/devescops:$IMAGE_TAG .
    - docker push devsecjs/devescops:$IMAGE_TAG