variables:
  IMAGE_NAME: sevgidogan/docker101tutorial
  IMAGE_TAG: juice-shop-1.0

stages:
  - test
  - build

yarn_test:
  image: node:18-bulleye
  stage: test
  script:
    - yarn install
    - yarn test
    
build_image:
    stage: build
    image: docker:24
    services:
      - docker:24-dind
    variables:
      DOCKER_PASS: dckr_pat_eHXX8WF4dnvDcOCXtEHbr4unYTI
      DOCKER_USER: sevgidogan
    before_script:
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin 
    script:
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker push $IMAGE_NAME:$IMAGE_TAG

