variables:
  IMAGE_NAME: spaceblocktechnology/akin
  IMAGE_TAG: juice-shop-1.1

stages:
  - cache
  - test
  - build

create_cache:
  image: node:18-bullseye
  stage: cache
  script:
    - yarn install
  cache:
    key: 
      files:
         - yarn.lock
      paths:
        - node_modules/
        - yarn.lock 
        - .yarn
      policy: pull-push

yarn_test:
  image: node:18-bullseye
  stage: test
  script:
    - yarn install
    - yarn test

build_image:
  stage: build
  image: docker:24
  services: 
    - docker:24-dind
  variables:
    DOCKER_PASS: akinlawon
    DOCKER_USER: spaceblocktechnology@gmail.com
  before_script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - docker buildx build -t $IMAGE_NAME:$IMAGE_TAG .

